=== queenns/wechat/wechat-tool/src/main/resources/xsd/wechat-info-wrapper.xsd
<?xml version="1.0" encoding="UTF-8" standalone="no"?>

<xsd:schema xmlns="http://www.queenns.org/schema/wrapper"
            xmlns:xsd="http://www.w3.org/2001/XMLSchema"
            targetNamespace="http://www.queenns.org/schema/wrapper">

    <xsd:import namespace="http://www.w3.org/XML/1998/namespace"/>

    <xsd:annotation>
        <xsd:documentation><![CDATA[
	wechat-rule-defined xml schema, version 1.0
	Authors: queenns

	wechat interface abstract encapsulation
        ]]></xsd:documentation>
    </xsd:annotation>


    <xsd:element name="wrapper" type="wrapperType">
        <xsd:annotation>
            <xsd:documentation><![CDATA[
	The top level (typically root) element. Allows the definition
    of default values for all nested defined definitions.
			]]></xsd:documentation>
        </xsd:annotation>
    </xsd:element>

    <xsd:complexType name="wrapperType">
        <xsd:sequence maxOccurs="unbounded">
            <xsd:element ref="group"/>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:element name="group" type="groupType"/>

    <xsd:complexType name="groupType">
        <xsd:sequence maxOccurs="unbounded">
            <xsd:element ref="information"/>
        </xsd:sequence>
        <xsd:attribute name="id" type="xsd:ID" use="required"/>
    </xsd:complexType>

    <xsd:element name="information" type="informationType"/>

    <xsd:complexType name="informationType">
        <xsd:sequence>
            <xsd:element ref="method"/>
            <xsd:element ref="url"/>
        </xsd:sequence>
        <xsd:attribute name="id" type="xsd:ID" use="required"/>
    </xsd:complexType>

    <xsd:element name="method" type="methodType">
        <xsd:annotation>
            <xsd:documentation><![CDATA[
	http type GET:POST:PUT:etc
			]]></xsd:documentation>
        </xsd:annotation>
    </xsd:element>

    <xsd:simpleType name="methodType">
        <xsd:restriction base="xsd:string">
            <xsd:enumeration value="GET"/>
            <xsd:enumeration value="POST"/>
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:element name="url" type="urlType"/>

    <xsd:simpleType name="urlType">
        <xsd:restriction base="xsd:anyURI"/>
    </xsd:simpleType>

</xsd:schema>

=== queenns/wechat/wechat-tool/src/main/resources/wechat-rule-define.xml
<?xml version="1.0" encoding="UTF-8"?>
<wrapper xmlns="http://www.queenns.org/schema/wrapper"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://www.queenns.org/schema/wrapper http://www.queenns.org/schema/wrapper/wechat-info-wrapper.xsd">
    <!--核心接口-->
    <group id="main">
        <!--accessToken-->
        <information id="accessToken">
            <method>GET</method>
            <url><![CDATA[https://api.weixin.qq.com/cgi-bin/token]]></url>
        </information>
    </group>

    <!--自定义菜单-->
    <group id="menu">

        <!--自定义菜单创建接口-->
        <information id="createMenu">
            <method>POST</method>
            <url><![CDATA[https://api.weixin.qq.com/cgi-bin/menu/create?access_token=ACCESS_TOKEN]]></url>
        </information>

        <!--自定义菜单查询接口-->
        <information id="findMenu">
            <method>POST</method>
            <url><![CDATA[https://api.weixin.qq.com/cgi-bin/menu/get?access_token=ACCESS_TOKEN]]></url>
        </information>

        <!--自定义菜单删除接口-->
        <information id="deleteMenu">
            <method>GET</method>
            <url><![CDATA[https://api.weixin.qq.com/cgi-bin/menu/delete?access_token=ACCESS_TOKEN]]></url>
        </information>

        <!--个性化菜单创建接口-->
        <information id="specialCreateMenu">
            <method>POST</method>
            <url><![CDATA[https://api.weixin.qq.com/cgi-bin/menu/addconditional?access_token=ACCESS_TOKEN]]></url>
        </information>

        <!--个性化菜单删除接口-->
        <information id="specialDeleteMenu">
            <method>POST</method>
            <url><![CDATA[https://api.weixin.qq.com/cgi-bin/menu/delconditional?access_token=ACCESS_TOKEN]]></url>
        </information>

        <!--个性化菜单匹配接口-->
        <information id="specialMatchConfigMenu">
            <method>POST</method>
            <url><![CDATA[https://api.weixin.qq.com/cgi-bin/menu/trymatch?access_token=ACCESS_TOKEN]]></url>
        </information>

    </group>

    <group id="material">

        <information id="createTemporaryMaterial">
            <method>POST</method>
            <url> <![CDATA[https://api.weixin.qq.com/cgi-bin/media/upload?access_token=ACCESS_TOKEN&type=TYPE]]></url>
        </information>

        <information id="findTemporaryMaterial">
            <method>GET</method>
            <url>
                <![CDATA[https://api.weixin.qq.com/cgi-bin/media/get?access_token=ACCESS_TOKEN&media_id=MEDIA_ID]]></url>
        </information>

    </group>

</wrapper>
